package dream

import (
	"github.com/Necroforger/discordgo"
	"sync"
)

// -------------------------------------
// Do not edit: Generated by tools/nextevent
// --------------------------------------

// NextChannelCreate returns the next ChannelCreate event
func (b *Bot) NextChannelCreate() *discordgo.ChannelCreate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.ChannelCreate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelCreate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextChannelDelete returns the next ChannelDelete event
func (b *Bot) NextChannelDelete() *discordgo.ChannelDelete {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.ChannelDelete
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelDelete) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextChannelPinsUpdate returns the next ChannelPinsUpdate event
func (b *Bot) NextChannelPinsUpdate() *discordgo.ChannelPinsUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.ChannelPinsUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelPinsUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextChannelUpdate returns the next ChannelUpdate event
func (b *Bot) NextChannelUpdate() *discordgo.ChannelUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.ChannelUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextConnect returns the next Connect event
func (b *Bot) NextConnect() *discordgo.Connect {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.Connect
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Connect) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextDisconnect returns the next Disconnect event
func (b *Bot) NextDisconnect() *discordgo.Disconnect {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.Disconnect
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Disconnect) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextEvent returns the next Event event
func (b *Bot) NextEvent() *discordgo.Event {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.Event
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Event) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildBanAdd returns the next GuildBanAdd event
func (b *Bot) NextGuildBanAdd() *discordgo.GuildBanAdd {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildBanAdd
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildBanAdd) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildBanRemove returns the next GuildBanRemove event
func (b *Bot) NextGuildBanRemove() *discordgo.GuildBanRemove {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildBanRemove
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildBanRemove) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildCreate returns the next GuildCreate event
func (b *Bot) NextGuildCreate() *discordgo.GuildCreate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildCreate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildCreate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildDelete returns the next GuildDelete event
func (b *Bot) NextGuildDelete() *discordgo.GuildDelete {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildDelete
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildDelete) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildEmojisUpdate returns the next GuildEmojisUpdate event
func (b *Bot) NextGuildEmojisUpdate() *discordgo.GuildEmojisUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildEmojisUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildEmojisUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildIntegrationsUpdate returns the next GuildIntegrationsUpdate event
func (b *Bot) NextGuildIntegrationsUpdate() *discordgo.GuildIntegrationsUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildIntegrationsUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildIntegrationsUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildMemberAdd returns the next GuildMemberAdd event
func (b *Bot) NextGuildMemberAdd() *discordgo.GuildMemberAdd {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildMemberAdd
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberAdd) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildMemberRemove returns the next GuildMemberRemove event
func (b *Bot) NextGuildMemberRemove() *discordgo.GuildMemberRemove {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildMemberRemove
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberRemove) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildMemberUpdate returns the next GuildMemberUpdate event
func (b *Bot) NextGuildMemberUpdate() *discordgo.GuildMemberUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildMemberUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildMembersChunk returns the next GuildMembersChunk event
func (b *Bot) NextGuildMembersChunk() *discordgo.GuildMembersChunk {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildMembersChunk
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMembersChunk) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildRoleCreate returns the next GuildRoleCreate event
func (b *Bot) NextGuildRoleCreate() *discordgo.GuildRoleCreate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildRoleCreate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleCreate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildRoleDelete returns the next GuildRoleDelete event
func (b *Bot) NextGuildRoleDelete() *discordgo.GuildRoleDelete {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildRoleDelete
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleDelete) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildRoleUpdate returns the next GuildRoleUpdate event
func (b *Bot) NextGuildRoleUpdate() *discordgo.GuildRoleUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildRoleUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextGuildUpdate returns the next GuildUpdate event
func (b *Bot) NextGuildUpdate() *discordgo.GuildUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.GuildUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageAck returns the next MessageAck event
func (b *Bot) NextMessageAck() *discordgo.MessageAck {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageAck
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageAck) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageCreate returns the next MessageCreate event
func (b *Bot) NextMessageCreate() *discordgo.MessageCreate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageCreate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageCreate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageDelete returns the next MessageDelete event
func (b *Bot) NextMessageDelete() *discordgo.MessageDelete {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageDelete
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageDelete) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageDeleteBulk returns the next MessageDeleteBulk event
func (b *Bot) NextMessageDeleteBulk() *discordgo.MessageDeleteBulk {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageDeleteBulk
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageDeleteBulk) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageReactionAdd returns the next MessageReactionAdd event
func (b *Bot) NextMessageReactionAdd() *discordgo.MessageReactionAdd {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageReactionAdd
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionAdd) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageReactionRemove returns the next MessageReactionRemove event
func (b *Bot) NextMessageReactionRemove() *discordgo.MessageReactionRemove {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageReactionRemove
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionRemove) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageReactionRemoveAll returns the next MessageReactionRemoveAll event
func (b *Bot) NextMessageReactionRemoveAll() *discordgo.MessageReactionRemoveAll {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageReactionRemoveAll
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionRemoveAll) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextMessageUpdate returns the next MessageUpdate event
func (b *Bot) NextMessageUpdate() *discordgo.MessageUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.MessageUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextPresenceUpdate returns the next PresenceUpdate event
func (b *Bot) NextPresenceUpdate() *discordgo.PresenceUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.PresenceUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.PresenceUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextPresencesReplace returns the next PresencesReplace event
func (b *Bot) NextPresencesReplace() *discordgo.PresencesReplace {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.PresencesReplace
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.PresencesReplace) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextRateLimit returns the next RateLimit event
func (b *Bot) NextRateLimit() *discordgo.RateLimit {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.RateLimit
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RateLimit) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextReady returns the next Ready event
func (b *Bot) NextReady() *discordgo.Ready {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.Ready
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Ready) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextRelationshipAdd returns the next RelationshipAdd event
func (b *Bot) NextRelationshipAdd() *discordgo.RelationshipAdd {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.RelationshipAdd
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RelationshipAdd) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextRelationshipRemove returns the next RelationshipRemove event
func (b *Bot) NextRelationshipRemove() *discordgo.RelationshipRemove {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.RelationshipRemove
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RelationshipRemove) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextResumed returns the next Resumed event
func (b *Bot) NextResumed() *discordgo.Resumed {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.Resumed
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Resumed) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextTypingStart returns the next TypingStart event
func (b *Bot) NextTypingStart() *discordgo.TypingStart {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.TypingStart
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.TypingStart) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextUserGuildSettingsUpdate returns the next UserGuildSettingsUpdate event
func (b *Bot) NextUserGuildSettingsUpdate() *discordgo.UserGuildSettingsUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.UserGuildSettingsUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserGuildSettingsUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextUserNoteUpdate returns the next UserNoteUpdate event
func (b *Bot) NextUserNoteUpdate() *discordgo.UserNoteUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.UserNoteUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserNoteUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextUserSettingsUpdate returns the next UserSettingsUpdate event
func (b *Bot) NextUserSettingsUpdate() *discordgo.UserSettingsUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.UserSettingsUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserSettingsUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextUserUpdate returns the next UserUpdate event
func (b *Bot) NextUserUpdate() *discordgo.UserUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.UserUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextVoiceServerUpdate returns the next VoiceServerUpdate event
func (b *Bot) NextVoiceServerUpdate() *discordgo.VoiceServerUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.VoiceServerUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.VoiceServerUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextVoiceStateUpdate returns the next VoiceStateUpdate event
func (b *Bot) NextVoiceStateUpdate() *discordgo.VoiceStateUpdate {
	var wg sync.WaitGroup
	wg.Add(1)
	var event *discordgo.VoiceStateUpdate
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.VoiceStateUpdate) {
		event = e
		wg.Done()
	})
	wg.Wait()
	return event
}

// NextChannelCreateC returns a channel for the next ChannelCreate event
func (b *Bot) NextChannelCreateC() chan *discordgo.ChannelCreate {
	out := make(chan *discordgo.ChannelCreate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelCreate) {
		out <- e
	})
	return out
}

// NextChannelDeleteC returns a channel for the next ChannelDelete event
func (b *Bot) NextChannelDeleteC() chan *discordgo.ChannelDelete {
	out := make(chan *discordgo.ChannelDelete)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelDelete) {
		out <- e
	})
	return out
}

// NextChannelPinsUpdateC returns a channel for the next ChannelPinsUpdate event
func (b *Bot) NextChannelPinsUpdateC() chan *discordgo.ChannelPinsUpdate {
	out := make(chan *discordgo.ChannelPinsUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelPinsUpdate) {
		out <- e
	})
	return out
}

// NextChannelUpdateC returns a channel for the next ChannelUpdate event
func (b *Bot) NextChannelUpdateC() chan *discordgo.ChannelUpdate {
	out := make(chan *discordgo.ChannelUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.ChannelUpdate) {
		out <- e
	})
	return out
}

// NextConnectC returns a channel for the next Connect event
func (b *Bot) NextConnectC() chan *discordgo.Connect {
	out := make(chan *discordgo.Connect)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Connect) {
		out <- e
	})
	return out
}

// NextDisconnectC returns a channel for the next Disconnect event
func (b *Bot) NextDisconnectC() chan *discordgo.Disconnect {
	out := make(chan *discordgo.Disconnect)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Disconnect) {
		out <- e
	})
	return out
}

// NextEventC returns a channel for the next Event event
func (b *Bot) NextEventC() chan *discordgo.Event {
	out := make(chan *discordgo.Event)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Event) {
		out <- e
	})
	return out
}

// NextGuildBanAddC returns a channel for the next GuildBanAdd event
func (b *Bot) NextGuildBanAddC() chan *discordgo.GuildBanAdd {
	out := make(chan *discordgo.GuildBanAdd)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildBanAdd) {
		out <- e
	})
	return out
}

// NextGuildBanRemoveC returns a channel for the next GuildBanRemove event
func (b *Bot) NextGuildBanRemoveC() chan *discordgo.GuildBanRemove {
	out := make(chan *discordgo.GuildBanRemove)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildBanRemove) {
		out <- e
	})
	return out
}

// NextGuildCreateC returns a channel for the next GuildCreate event
func (b *Bot) NextGuildCreateC() chan *discordgo.GuildCreate {
	out := make(chan *discordgo.GuildCreate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildCreate) {
		out <- e
	})
	return out
}

// NextGuildDeleteC returns a channel for the next GuildDelete event
func (b *Bot) NextGuildDeleteC() chan *discordgo.GuildDelete {
	out := make(chan *discordgo.GuildDelete)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildDelete) {
		out <- e
	})
	return out
}

// NextGuildEmojisUpdateC returns a channel for the next GuildEmojisUpdate event
func (b *Bot) NextGuildEmojisUpdateC() chan *discordgo.GuildEmojisUpdate {
	out := make(chan *discordgo.GuildEmojisUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildEmojisUpdate) {
		out <- e
	})
	return out
}

// NextGuildIntegrationsUpdateC returns a channel for the next GuildIntegrationsUpdate event
func (b *Bot) NextGuildIntegrationsUpdateC() chan *discordgo.GuildIntegrationsUpdate {
	out := make(chan *discordgo.GuildIntegrationsUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildIntegrationsUpdate) {
		out <- e
	})
	return out
}

// NextGuildMemberAddC returns a channel for the next GuildMemberAdd event
func (b *Bot) NextGuildMemberAddC() chan *discordgo.GuildMemberAdd {
	out := make(chan *discordgo.GuildMemberAdd)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberAdd) {
		out <- e
	})
	return out
}

// NextGuildMemberRemoveC returns a channel for the next GuildMemberRemove event
func (b *Bot) NextGuildMemberRemoveC() chan *discordgo.GuildMemberRemove {
	out := make(chan *discordgo.GuildMemberRemove)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberRemove) {
		out <- e
	})
	return out
}

// NextGuildMemberUpdateC returns a channel for the next GuildMemberUpdate event
func (b *Bot) NextGuildMemberUpdateC() chan *discordgo.GuildMemberUpdate {
	out := make(chan *discordgo.GuildMemberUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMemberUpdate) {
		out <- e
	})
	return out
}

// NextGuildMembersChunkC returns a channel for the next GuildMembersChunk event
func (b *Bot) NextGuildMembersChunkC() chan *discordgo.GuildMembersChunk {
	out := make(chan *discordgo.GuildMembersChunk)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildMembersChunk) {
		out <- e
	})
	return out
}

// NextGuildRoleCreateC returns a channel for the next GuildRoleCreate event
func (b *Bot) NextGuildRoleCreateC() chan *discordgo.GuildRoleCreate {
	out := make(chan *discordgo.GuildRoleCreate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleCreate) {
		out <- e
	})
	return out
}

// NextGuildRoleDeleteC returns a channel for the next GuildRoleDelete event
func (b *Bot) NextGuildRoleDeleteC() chan *discordgo.GuildRoleDelete {
	out := make(chan *discordgo.GuildRoleDelete)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleDelete) {
		out <- e
	})
	return out
}

// NextGuildRoleUpdateC returns a channel for the next GuildRoleUpdate event
func (b *Bot) NextGuildRoleUpdateC() chan *discordgo.GuildRoleUpdate {
	out := make(chan *discordgo.GuildRoleUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildRoleUpdate) {
		out <- e
	})
	return out
}

// NextGuildUpdateC returns a channel for the next GuildUpdate event
func (b *Bot) NextGuildUpdateC() chan *discordgo.GuildUpdate {
	out := make(chan *discordgo.GuildUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.GuildUpdate) {
		out <- e
	})
	return out
}

// NextMessageAckC returns a channel for the next MessageAck event
func (b *Bot) NextMessageAckC() chan *discordgo.MessageAck {
	out := make(chan *discordgo.MessageAck)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageAck) {
		out <- e
	})
	return out
}

// NextMessageCreateC returns a channel for the next MessageCreate event
func (b *Bot) NextMessageCreateC() chan *discordgo.MessageCreate {
	out := make(chan *discordgo.MessageCreate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageCreate) {
		out <- e
	})
	return out
}

// NextMessageDeleteC returns a channel for the next MessageDelete event
func (b *Bot) NextMessageDeleteC() chan *discordgo.MessageDelete {
	out := make(chan *discordgo.MessageDelete)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageDelete) {
		out <- e
	})
	return out
}

// NextMessageDeleteBulkC returns a channel for the next MessageDeleteBulk event
func (b *Bot) NextMessageDeleteBulkC() chan *discordgo.MessageDeleteBulk {
	out := make(chan *discordgo.MessageDeleteBulk)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageDeleteBulk) {
		out <- e
	})
	return out
}

// NextMessageReactionAddC returns a channel for the next MessageReactionAdd event
func (b *Bot) NextMessageReactionAddC() chan *discordgo.MessageReactionAdd {
	out := make(chan *discordgo.MessageReactionAdd)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionAdd) {
		out <- e
	})
	return out
}

// NextMessageReactionRemoveC returns a channel for the next MessageReactionRemove event
func (b *Bot) NextMessageReactionRemoveC() chan *discordgo.MessageReactionRemove {
	out := make(chan *discordgo.MessageReactionRemove)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionRemove) {
		out <- e
	})
	return out
}

// NextMessageReactionRemoveAllC returns a channel for the next MessageReactionRemoveAll event
func (b *Bot) NextMessageReactionRemoveAllC() chan *discordgo.MessageReactionRemoveAll {
	out := make(chan *discordgo.MessageReactionRemoveAll)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageReactionRemoveAll) {
		out <- e
	})
	return out
}

// NextMessageUpdateC returns a channel for the next MessageUpdate event
func (b *Bot) NextMessageUpdateC() chan *discordgo.MessageUpdate {
	out := make(chan *discordgo.MessageUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.MessageUpdate) {
		out <- e
	})
	return out
}

// NextPresenceUpdateC returns a channel for the next PresenceUpdate event
func (b *Bot) NextPresenceUpdateC() chan *discordgo.PresenceUpdate {
	out := make(chan *discordgo.PresenceUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.PresenceUpdate) {
		out <- e
	})
	return out
}

// NextPresencesReplaceC returns a channel for the next PresencesReplace event
func (b *Bot) NextPresencesReplaceC() chan *discordgo.PresencesReplace {
	out := make(chan *discordgo.PresencesReplace)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.PresencesReplace) {
		out <- e
	})
	return out
}

// NextRateLimitC returns a channel for the next RateLimit event
func (b *Bot) NextRateLimitC() chan *discordgo.RateLimit {
	out := make(chan *discordgo.RateLimit)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RateLimit) {
		out <- e
	})
	return out
}

// NextReadyC returns a channel for the next Ready event
func (b *Bot) NextReadyC() chan *discordgo.Ready {
	out := make(chan *discordgo.Ready)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Ready) {
		out <- e
	})
	return out
}

// NextRelationshipAddC returns a channel for the next RelationshipAdd event
func (b *Bot) NextRelationshipAddC() chan *discordgo.RelationshipAdd {
	out := make(chan *discordgo.RelationshipAdd)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RelationshipAdd) {
		out <- e
	})
	return out
}

// NextRelationshipRemoveC returns a channel for the next RelationshipRemove event
func (b *Bot) NextRelationshipRemoveC() chan *discordgo.RelationshipRemove {
	out := make(chan *discordgo.RelationshipRemove)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.RelationshipRemove) {
		out <- e
	})
	return out
}

// NextResumedC returns a channel for the next Resumed event
func (b *Bot) NextResumedC() chan *discordgo.Resumed {
	out := make(chan *discordgo.Resumed)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.Resumed) {
		out <- e
	})
	return out
}

// NextTypingStartC returns a channel for the next TypingStart event
func (b *Bot) NextTypingStartC() chan *discordgo.TypingStart {
	out := make(chan *discordgo.TypingStart)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.TypingStart) {
		out <- e
	})
	return out
}

// NextUserGuildSettingsUpdateC returns a channel for the next UserGuildSettingsUpdate event
func (b *Bot) NextUserGuildSettingsUpdateC() chan *discordgo.UserGuildSettingsUpdate {
	out := make(chan *discordgo.UserGuildSettingsUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserGuildSettingsUpdate) {
		out <- e
	})
	return out
}

// NextUserNoteUpdateC returns a channel for the next UserNoteUpdate event
func (b *Bot) NextUserNoteUpdateC() chan *discordgo.UserNoteUpdate {
	out := make(chan *discordgo.UserNoteUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserNoteUpdate) {
		out <- e
	})
	return out
}

// NextUserSettingsUpdateC returns a channel for the next UserSettingsUpdate event
func (b *Bot) NextUserSettingsUpdateC() chan *discordgo.UserSettingsUpdate {
	out := make(chan *discordgo.UserSettingsUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserSettingsUpdate) {
		out <- e
	})
	return out
}

// NextUserUpdateC returns a channel for the next UserUpdate event
func (b *Bot) NextUserUpdateC() chan *discordgo.UserUpdate {
	out := make(chan *discordgo.UserUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.UserUpdate) {
		out <- e
	})
	return out
}

// NextVoiceServerUpdateC returns a channel for the next VoiceServerUpdate event
func (b *Bot) NextVoiceServerUpdateC() chan *discordgo.VoiceServerUpdate {
	out := make(chan *discordgo.VoiceServerUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.VoiceServerUpdate) {
		out <- e
	})
	return out
}

// NextVoiceStateUpdateC returns a channel for the next VoiceStateUpdate event
func (b *Bot) NextVoiceStateUpdateC() chan *discordgo.VoiceStateUpdate {
	out := make(chan *discordgo.VoiceStateUpdate)
	b.DG.AddHandlerOnce(func(s *discordgo.Session, e *discordgo.VoiceStateUpdate) {
		out <- e
	})
	return out
}
