package main

import (
	"bytes"
	"go/format"
	"go/parser"
	"go/token"
	"io/ioutil"
	"log"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

var eventHandlerTmpl = template.Must(template.New("eventHandler").Funcs(template.FuncMap{
	"constName":      constName,
	"isDiscordEvent": isDiscordEvent,
	"privateName":    privateName,
}).Parse(`package dream

import (
	"bytes"
	"fmt"

	"github.com/BurntSushi/toml"
	"github.com/Necroforger/discordgo"
	"strings"
)
// -------------------------------------
// Do not edit: Generated by tools/listeners
// --------------------------------------

// LoggingConfig is configuration for what events to track
type LoggingConfig struct {
	{{- range .}}{{if isDiscordEvent .}}
	{{.}} bool
	{{- end}}{{end}}
}

{{range .}}{{if isDiscordEvent .}}
// log{{.}} Logs all {{.}} events received from the session
func (b *Bot) log{{.}}(s *discordgo.Session, e *discordgo.{{.}}) {
	var dat = bytes.Buffer{}
	err := toml.NewEncoder(&dat).Encode(e)
	if err != nil {
		return
	}
	b.Log(0, fmt.Sprint("{{constName .}}: \n\t", strings.Replace(string(dat.Bytes()), "\n", "\n\t", -1)))
}
{{end}}{{end}}


func (b *Bot) registerListeners(conf LoggingConfig) {
	{{- range .}}{{if isDiscordEvent .}}
	if conf.{{.}} {
		b.DG.AddHandler(b.log{{.}})
	}
	{{- end}}{{end}}
}
	
`))

func main() {
	var buf bytes.Buffer
	dir := filepath.Dir(".")

	fs := token.NewFileSet()
	parsedFile, err := parser.ParseFile(fs, "tools/events.txt", nil, 0)
	if err != nil {
		log.Fatalf("warning: internal error: could not parse events.txt: %s", err)
		return
	}

	names := []string{}
	for object := range parsedFile.Scope.Objects {
		names = append(names, object)
	}

	sort.Strings(names)
	eventHandlerTmpl.Execute(&buf, names)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Println("warning: internal error: invalid Go generated:", err)
		src = buf.Bytes()
	}

	err = ioutil.WriteFile(filepath.Join(dir, strings.ToLower("listeners.go")), src, 0644)
	if err != nil {
		log.Fatal(buf, "writing output: %s", err)
	}
}

var constRegexp = regexp.MustCompile("([a-z])([A-Z])")

func constCase(name string) string {
	return strings.ToUpper(constRegexp.ReplaceAllString(name, "${1}_${2}"))
}

func isDiscordEvent(name string) bool {
	switch {
	case name == "Connect", name == "Disconnect", name == "Event", name == "RateLimit", name == "Interface":
		return false
	default:
		return true
	}
}

func constName(name string) string {
	if !isDiscordEvent(name) {
		return "__" + constCase(name) + "__"
	}

	return constCase(name)
}

func privateName(name string) string {
	return strings.ToLower(string(name[0])) + name[1:]
}
